baseURL = 'http://localhost:1313/'
languageCode = 'vi'
title = 'Taf1 IT BLOG'
theme = ''

[params]
  author = 'Nguyễn Thành Tài'
  description = 'Blog Lập Trình Mạng'
  email = 'nguyenthanhtai270604@gmail.com'
  phone = '+84 924 140 389'

[permalinks]
  blog = '/blog/:filename/'

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
